const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base='http://127.0.0.1:8767/builder/',checks=[];
function check(name,ok){assert.ok(ok,name);checks.push(name);console.log('PASS',name);}
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{
 const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(base);await p.waitForFunction(()=>window.NebulaApp?.ready);await p.waitForFunction(()=>document.querySelectorAll('[data-template]:not(:disabled)').length===10);
 check('Three Halloween cards alongside the seven existing recipes',await p.locator('#halloweenTemplateCards [data-template]').count()===3);
 for(const [id,count] of [['scream-for-you',30],['forever-my-boo',44],['midnight-blooms',20]]){
  await p.evaluate(id=>NebulaApp.applyFallTemplate(id),id);await p.evaluate(()=>NebulaRenderer.awaitAssets(NebulaApp.state));
  check(id+': valid state, exact flower count, and loaded artwork',await p.evaluate(count=>{const s=NebulaApp.state,sc=NebulaApp.scene();return !!NebulaModel.validate(s)&&s.items.length===count&&sc.nodes.length===count&&[...NebulaRenderer.assetsFor(s)].every(NebulaRenderer.decoded);},count));
  check(id+': exact scene and price survive sharing',await p.evaluate(()=>{const s=NebulaApp.state,d=NebulaLink.decode(NebulaLink.encode(s))?.design;return d&&JSON.stringify(NebulaRenderer.scene(s))===JSON.stringify(NebulaRenderer.scene(d))&&JSON.stringify(NebulaModel.price(s))===JSON.stringify(NebulaModel.price(d));}));
  check(id+': every flower remains visible beneath overlapping petals and details',await p.evaluate(()=>{const s=NebulaApp.state,R=NebulaRenderer,sc=R.scene(s);function pixels(scene){const cv=R.makeCanvas(),ctx=cv.getContext('2d');R.drawArt(ctx,s,{scene});return ctx.getImageData(0,0,720,820).data;}const full=pixels(sc);return sc.nodes.every(n=>{const partial=pixels({...sc,nodes:sc.nodes.filter(m=>m.uid!==n.uid)});let changed=0;for(let i=0;i<full.length;i+=4)if(Math.abs(full[i]-partial[i])+Math.abs(full[i+1]-partial[i+1])+Math.abs(full[i+2]-partial[i+2])>24)changed++;return changed>40;});}));
  check(id+': resize cannot silently destroy the composition',await p.evaluate(()=>{const s=NebulaApp.state,before=JSON.stringify(s);return !NebulaModel.resize(s,62).ok&&JSON.stringify(s)===before;}));
  const png=await p.evaluate(async()=>Array.from(new Uint8Array(await(await NebulaApp.exportBlob(1080,1080)).arrayBuffer())));fs.writeFileSync(path.join(__dirname,id+'.png'),Buffer.from(png));
 }
 await p.evaluate(()=>NebulaApp.applyFallTemplate('scream-for-you'));await p.locator('#tab-finishing').click();
 const price=await p.evaluate(()=>NebulaModel.price(NebulaApp.state).totalCents);await p.locator('#spookyMask').uncheck();
 check('Removing mask removes one priced mask and preserves 30 flowers',await p.evaluate(price=>!NebulaApp.scene().finishes.some(n=>n.uid==='scream-mask')&&NebulaApp.state.items.length===30&&NebulaModel.price(NebulaApp.state).totalCents===price-NebulaConfig.CONFIG.extrasCents.spookyMask,price));
 await p.locator('#undo').click();check('Mask toggle is undoable',await p.locator('#spookyMask').isChecked());
 for(let i=0;i<3;i++)await p.locator('#fillerLess').click();
 check('Filler quantity controls rendered and billed sprigs together',await p.evaluate(()=>NebulaApp.scene().filler.length===3&&NebulaModel.price(NebulaApp.state).extraLines.find(l=>l.id==='filler').quantity===3));
 check('Oversized flower replacement and swap are rejected atomically',await p.evaluate(()=>{const M=NebulaModel,s=NebulaApp.state,before=JSON.stringify(s);if(M.paintSlot(s,0,'lily').ok||JSON.stringify(s)!==before)return false;const m=NebulaSpooky.create('midnight-blooms'),copy=JSON.stringify(m),target=m.items.find(n=>n.id==='rose_black');return !M.move(m,'b1',target.anchors.dome).ok&&JSON.stringify(m)===copy;}));
 await p.evaluate(()=>NebulaApp.paintSlot(0,'rose_black'));check('Compatible rose replacement is editable',await p.evaluate(()=>NebulaApp.state.items.find(n=>n.slot===0).id==='rose_black'));await p.locator('#undo').click();
 check('Deleting a flower subtracts exactly one stem price and leaves its slot available',await p.evaluate(()=>{const s=NebulaApp.state,p=NebulaModel.price(s).totalCents;NebulaModel.remove(s,'b1');return s.items.length===29&&NebulaModel.price(s).totalCents===p-NebulaConfig.CAT.rose_red.priceCents&&NebulaModel.paintSlot(s,0,'rose_red').ok&&s.items.length===30;}));
 await p.evaluate(()=>NebulaApp.applyFallTemplate('forever-my-boo'));await p.locator('#tab-finishing').click();await p.locator('#ghostCount').fill('2');await p.locator('#ghostCount').dispatchEvent('change');await p.locator('#sashText').fill('MY FAVORITE GHOST');await p.locator('#sashText').blur();
 check('Ghost controls and custom sash survive sharing',await p.evaluate(()=>{const s=NebulaLink.decode(NebulaLink.encode(NebulaApp.state)).design;return s.finishes.ghostCount===2&&s.finishes.sashText==='MY FAVORITE GHOST'&&NebulaRenderer.scene(s).finishes.filter(n=>n.back).length===2&&NebulaModel.price(s).extraLines.find(l=>l.id==='ghostCount').quantity===2;}));
 const code=await p.evaluate(()=>NebulaLink.encode(NebulaApp.state)),sheet=await ctx.newPage();sheet.on('pageerror',e=>errors.push(e.message));await sheet.goto(base+'order.html#b='+code);await sheet.waitForSelector('#orderSheet:not([hidden])');check('Florist sheet includes ghost quantity and custom message',await sheet.locator('#osFinishes').innerText().then(t=>t.includes('Ghost decals: × 2')&&t.includes('MY FAVORITE GHOST')));await sheet.close();
 const saved=await p.evaluate(()=>JSON.stringify(NebulaApp.state));await p.reload();await p.waitForFunction(()=>NebulaApp?.ready);check('Reload preserves the edited Halloween design',await p.evaluate(()=>JSON.stringify(NebulaApp.state))===saved);
 await p.evaluate(()=>NebulaApp.applyFallTemplate('midnight-blooms'));await p.locator('#tab-finishing').click();await p.locator('#thistleCount').fill('1');await p.locator('#thistleCount').dispatchEvent('change');
 check('Blue accents are separately counted, with no missing topper charged',await p.evaluate(()=>{const s=NebulaApp.state,price=NebulaModel.price(s);return NebulaApp.scene().filler.length===1&&s.items.length===20&&price.extraLines.find(l=>l.id==='thistleCount').quantity===1&&!price.extraLines.some(l=>l.id.includes('jack'));}));
 check('Malformed recipes, extras, and large slot substitutions are rejected',await p.evaluate(()=>[s=>s.template.halloweenRecipe='unknown',s=>s.template.capacity=30,s=>s.finishes.thistleCount=4,s=>s.finishes.spookyMask='yes',s=>s.finishes.ghostCount=7,s=>s.template.overrides[8]='lily',s=>s.finishes.paper='invalid'].every(fn=>{const s=NebulaApp.state;fn(s);return !NebulaModel.validate(s);} )));
 for(const width of [320,390]){await p.setViewportSize({width,height:844});for(const id of ['scream-for-you','forever-my-boo','midnight-blooms']){await p.evaluate(id=>NebulaApp.applyFallTemplate(id),id);await p.evaluate(()=>NebulaRenderer.awaitAssets(NebulaApp.state));check(id+': '+width+'px viewport fits artwork and controls',await p.evaluate(()=>{const s=NebulaApp.state,R=NebulaRenderer,b=R.artBounds(s,R.scene(s)),v=R.view(s);return document.documentElement.scrollWidth<=innerWidth+1&&b.x*v.scale+v.x>=0&&b.y*v.scale+v.y>=0&&(b.x+b.w)*v.scale+v.x<=720&&(b.y+b.h)*v.scale+v.y<=820;}));}await p.screenshot({path:path.join(__dirname,'mobile-'+width+'.png'),fullPage:true});}
 await p.locator('#language').selectOption('es');await p.locator('#tab-finishing').click();check('Halloween finishing labels switch to Spanish',await p.locator('#thistleCountRow').innerText().then(t=>t.includes('Cardos azules')));
 const offline=await ctx.newPage();offline.on('pageerror',e=>errors.push(e.message));await offline.goto('file:///'+path.resolve(__dirname,'../../index.html').replaceAll('\\','/'));await offline.waitForFunction(()=>window.NebulaApp?.ready);check('All three recipes export from embedded offline assets',await offline.evaluate(async()=>{for(const r of NebulaSpooky.recipes){const s=NebulaSpooky.create(r.id),b=await NebulaRenderer.blob(s,540,540,'en');if(!b||b.size<10000||!NebulaSpooky.assets.every(url=>NebulaRenderer.source(url).startsWith('data:')))return false;}return true;}));await offline.close();
 check('No runtime errors in desktop, mobile, order sheet or offline export',errors.length===0);fs.writeFileSync(path.join(__dirname,'integration-results.json'),JSON.stringify({checks,errors},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
