const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),crypto=require('crypto'),{spawn}=require('child_process');const root=path.resolve(process.argv[2]),out=__dirname,results=[];let ctx,server;const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const runtimeHashes=Object.fromEntries(fs.readdirSync(root).filter(n=>/\.(js|html|css)$/.test(n)).map(n=>[n,sha(fs.readFileSync(path.join(root,n)))]));
function ck(label,pass,detail){results.push({label,pass:!!pass,detail});fs.writeFileSync(path.join(out,'clean-smoke.json'),JSON.stringify({passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,runtimeHashes,checks:results},null,2));console.log(pass?'PASS':'FAIL',label,detail??'');}
(async()=>{const b=await chromium.connectOverCDP(process.env.AGENT_BROWSER_CDP);const log=fs.openSync('/data/nebula-v6/clean-http.log','w');server=spawn('python3',['-m','http.server','8899','--bind','127.0.0.1','--directory',root],{stdio:['ignore',log,log]});let started=false;for(let n=0;n<30;n++){try{const res=await fetch('http://127.0.0.1:8899/index.html');if(res.ok){const html=await res.text();ck('HTTP serves the clean extraction, not the working tree',sha(Buffer.from(html))===runtimeHashes['index.html']);started=true;break;}}catch(e){}await new Promise(r=>setTimeout(r,100));}if(!started)throw Error('Clean HTTP server did not start');
for(const mode of ['file','http']){ctx=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,acceptDownloads:true});const p=await ctx.newPage(),errors=[],external=[];p.on('pageerror',e=>errors.push(e.message));await p.route(/^https?:\/\//,route=>{if(route.request().url().startsWith('http://127.0.0.1:8899/'))route.continue();else{external.push(route.request().url());route.abort();}});const url=mode==='file'?require('url').pathToFileURL(path.join(root,'index.html')).href:'http://127.0.0.1:8899/index.html';await p.goto(url);await p.waitForFunction(()=>window.NebulaApp?.ready);ck(mode+' starts the complete v6 builder',await p.evaluate(()=>NebulaApp.state.version===6&&NebulaApp.state.mode==='classic'&&Object.keys(NEBULA_EMBED).length===96));
await p.locator('[data-mode=dome]').tap();await p.locator('[data-size=Mini]').tap();await p.locator('#confirmYes').tap();await p.locator('#paintTool').tap();await p.locator('#family').selectOption('accents');await p.locator('#flowerGrid [data-flower=lily]').tap();for(let slot=0;slot<5;slot++){const q=await p.evaluate(slot=>{const s=NebulaApp.state,L=NebulaTemplates.layout(s.mode,s.template.capacity),a=L.points[slot],r=document.getElementById('bouquet').getBoundingClientRect(),v=NebulaRenderer.view(s,NebulaApp.camera);return {x:r.left+(v.x+(360+a.x)*v.scale)*r.width/720,y:r.top+(v.y+(390+a.y)*v.scale)*r.height/820};},slot);await p.touchscreen.tap(q.x,q.y);}
ck(mode+' five real taps preserve 15 slots and exact $100 estimate',await p.evaluate(()=>NebulaApp.state.template.capacity===15&&NebulaModel.counts(NebulaApp.state).lily===5&&NebulaModel.counts(NebulaApp.state).rose_red===10&&NebulaModel.price(NebulaApp.state).totalCents===10000));
await p.locator('#reviewButton').tap();const quote=await p.locator('#quoteText').inputValue();ck(mode+' quote is accurate and not an order',quote.includes('5 × Pink lily')&&quote.includes('10 × Red rose')&&quote.includes('NOT AN ORDER'));
const download=p.waitForEvent('download');await p.locator('#quoteImage').tap();const d=await download;await d.saveAs(path.join(out,'clean-'+mode+'-export.png'));const png=fs.readFileSync(path.join(out,'clean-'+mode+'-export.png'));ck(mode+' real PNG export works',png.length>10000&&png.subarray(1,4).toString()==='PNG');await p.locator('[data-close=quoteDialog]').tap();const before=await p.evaluate(()=>({state:NebulaApp.portfolio,ref:NebulaApp.makeQuote().reference}));await p.reload();await p.waitForFunction(()=>NebulaApp.ready);const after=await p.evaluate(()=>({state:NebulaApp.portfolio,ref:NebulaApp.makeQuote().reference}));ck(mode+' reload preserves the complete studio and quote reference',require('util').isDeepStrictEqual(before,after));ck(mode+' no runtime errors or external requests',!errors.length&&!external.length,{errors,external});await ctx.close();ctx=null;}
server.kill();console.log('COMPLETE',results.filter(r=>r.pass).length,'passed',results.filter(r=>!r.pass).length,'failed');process.exit(0);
})().catch(async e=>{console.error(e.stack);if(ctx)await ctx.close().catch(()=>{});if(server)server.kill();process.exit(1);});
