const APP_URL=require('url').pathToFileURL(require('path').join(process.env.NEBULA_TEST_ROOT||require('path').resolve(__dirname,'../..'),'index.html')).href;
const {chromium}=require('playwright'),fs=require('fs'),path=require('path');const root=__dirname,checks=[];let ctx,page;
const ck=(label,pass,detail)=>{checks.push({label,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',label,detail??'');fs.writeFileSync(path.join(root,'native-results.json'),JSON.stringify({passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass).length,checks},null,2));};
const ready=async()=>page.waitForFunction(()=>window.NebulaApp?.ready);
const coords=async slot=>page.evaluate(slot=>{const s=NebulaApp.state,L=NebulaTemplates.layout(s.mode,s.template.capacity),p=L.points[slot],r=document.getElementById('bouquet').getBoundingClientRect(),v=NebulaRenderer.view(s,NebulaApp.camera);return {x:r.left+(v.x+(360+p.x)*v.scale)*r.width/720,y:r.top+(v.y+(390+p.y)*v.scale)*r.height/820};},slot);
async function tapSlot(slot){const p=await coords(slot);await page.touchscreen.tap(p.x,p.y);}
(async()=>{const b=await chromium.connectOverCDP(process.env.AGENT_BROWSER_CDP);ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true,acceptDownloads:true});page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(APP_URL);await ready();
ck('Phone opens Classic',await page.evaluate(()=>NebulaApp.state.mode==='classic'));ck('No Replace buttons or replacement dialog',await page.locator('button').filter({hasText:/^Replace$/}).count()===0&&await page.locator('#pickerDialog').count()===0);
await page.locator('[data-mode=dome]').tap();ck('Dome opens independent 30-slot template',await page.evaluate(()=>NebulaApp.state.items.length===30&&NebulaApp.state.template.capacity===30));ck('No top-view add-one or arbitrary count controls',!await page.locator('#addOne').isVisible()&&!await page.locator('#startingDetails').isVisible());
await page.locator('[data-size=Mini]').tap();ck('Template size change is confirmed',await page.locator('#confirmDialog').isVisible());await page.locator('#confirmYes').tap();ck('Mini offers 15 fixed slots',await page.evaluate(()=>NebulaApp.state.template.capacity===15));const base=await page.evaluate(()=>NebulaModel.price(NebulaApp.state).totalCents);
await page.locator('#flowerGrid [data-flower=rose_white]').tap();ck('A palette card directly blends another variety',await page.evaluate(()=>NebulaModel.counts(NebulaApp.state).rose_white>0&&NebulaApp.state.items.length===15));await page.locator('#flowerGrid [data-flower=rose_white]').tap();
await page.locator('#paintTool').tap();await page.locator('#family').selectOption('accents');await page.locator('#flowerGrid [data-flower=lily]').tap();ck('Lily card selects a brush without a modal',await page.evaluate(()=>NebulaApp.brush==='lily')&&await page.locator('dialog[open]').count()===0);
for(let i=0;i<5;i++)await tapSlot(i);ck('Five real touch taps replace five roses with lilies',await page.evaluate(()=>NebulaModel.counts(NebulaApp.state).lily===5&&NebulaApp.state.items.length===15));ck('Touch changes update exact live price',await page.evaluate(()=>NebulaModel.price(NebulaApp.state).totalCents)===base+500);
await page.locator('#stopBrush').tap();await tapSlot(2);ck('Selecting a bloom shows its contextual X',await page.locator('#inlineDelete').isVisible());const box=await page.locator('#inlineDelete').boundingBox();ck('X has a 44px touch target',box.width>=44&&box.height>=44);await page.locator('#inlineDelete').tap();ck('X deletes exactly one lily, not the template slot',await page.evaluate(()=>NebulaApp.state.items.length===14&&NebulaApp.state.template.capacity===15&&NebulaApp.state.template.overrides[2]===null));
await page.locator('#undo').tap();ck('Undo restores the same slot and price',await page.evaluate(()=>NebulaModel.counts(NebulaApp.state).lily===5&&NebulaApp.state.items.length===15));await page.locator('#redo').tap();ck('Redo restores deletion',await page.evaluate(()=>NebulaApp.state.items.length===14));
await page.locator('#flowerGrid [data-flower=lily]').tap();await tapSlot(2);ck('Tapping the visible empty slot refills only it',await page.evaluate(()=>NebulaApp.state.items.length===15&&NebulaModel.counts(NebulaApp.state).lily===5));
// Native touch sweep, one undo unit; no coordinate setters used.
await page.locator('#flowerGrid [data-flower=gerbera_daisy]').tap();const before=await page.evaluate(()=>({history:NebulaApp.history.undo,design:NebulaApp.state}));const cd=await ctx.newCDPSession(page);let q=await coords(0);await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:q.x,y:q.y}]});for(const slot of [1,2,3]){q=await coords(slot);await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:q.x,y:q.y}]});}await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
ck('A touch sweep paints multiple slots',await page.evaluate(()=>NebulaModel.counts(NebulaApp.state).gerbera_daisy>=3));ck('A complete sweep is one Undo step',await page.evaluate(()=>NebulaApp.history.undo)===before.history+1);await page.locator('#undo').tap();ck('Undo restores entire pre-sweep design',await page.evaluate(()=>JSON.stringify(NebulaApp.state))===JSON.stringify(before.design));
await page.locator('#focusPreview').tap();ck('Expanded phone preview hides controls',!await page.locator('#controls').isVisible());await page.locator('#zoomIn').tap();await page.locator('#zoomIn').tap();ck('Preview zooms without changing the design',await page.evaluate(()=>NebulaApp.camera.zoom===2&&NebulaApp.state.items.length===15));await page.locator('#panView').tap();const cb=await page.locator('#bouquet').boundingBox();await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cb.x+cb.width*.5,y:cb.y+cb.height*.5}]});await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cb.x+cb.width*.65,y:cb.y+cb.height*.58}]});await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});ck('Move preview pans, never paints',await page.evaluate(()=>NebulaApp.camera.x!==0&&NebulaModel.counts(NebulaApp.state).lily===5));await page.locator('#resetView').tap();await page.locator('#focusPreview').tap();
await page.locator('[data-tab=finishing]').tap();await page.locator('#giftNote').fill('Dome request: five lilies.');await page.locator('#sash').selectOption('bday');await page.locator('#sashPosition').selectOption('low');await page.locator('[data-mode=heart]').tap();ck('Heart opens its independent v1-style 41-slot bouquet',await page.evaluate(()=>NebulaApp.state.items.length===41&&NebulaApp.state.note===''));await page.locator('[data-tab=flowers]').tap();await page.locator('#zoneWall').selectOption('rose_pink');await page.locator('#zoneFill').selectOption('rose_white');await page.locator('#zoneCenter').selectOption('lily');ck('Heart zones change directly, with one center',await page.evaluate(()=>NebulaModel.counts(NebulaApp.state).lily===1&&NebulaModel.counts(NebulaApp.state).rose_pink>0&&NebulaApp.state.items.length===41));await page.locator('#heartFormation').selectOption('rings');ck('Heart formation works without adding flowers',await page.evaluate(()=>NebulaApp.state.template.zones.formation==='rings'&&NebulaApp.state.items.length===41));
await page.locator('[data-size=XL]').tap();await page.locator('#confirmYes').tap();ck('XL heart keeps automatic zones and one center',await page.evaluate(()=>NebulaApp.state.template.capacity===100&&NebulaModel.counts(NebulaApp.state).lily===1&&NebulaModel.counts(NebulaApp.state).rose_pink>0&&Object.keys(NebulaApp.state.template.overrides).length===0));await page.locator('#zoneWall').selectOption('rose_violet');ck('Zones remain editable after resizing',await page.evaluate(()=>!NebulaModel.counts(NebulaApp.state).rose_pink&&NebulaModel.counts(NebulaApp.state).rose_violet>0));await page.locator('[data-size=M]').tap();await page.locator('#confirmYes').tap();await page.locator('#zoneWall').selectOption('rose_pink');
await page.locator('[data-mode=dome]').tap();ck('Dome composition, note and sash are remembered',await page.evaluate(()=>NebulaModel.counts(NebulaApp.state).lily===5&&NebulaApp.state.note==='Dome request: five lilies.'&&NebulaApp.state.finishes.sash==='bday'&&NebulaApp.state.finishes.sashPlacement==='low'));
const expected=await page.evaluate(()=>NebulaApp.portfolio);await page.reload();await ready();const reopened=await page.evaluate(()=>NebulaApp.portfolio);fs.writeFileSync(path.join(root,'reload-comparison.json'),JSON.stringify({before:expected,after:reopened},null,2));ck('Reopening preserves all three bouquets',require('util').isDeepStrictEqual(reopened,expected));
await page.locator('#reviewButton').tap();ck('Ask florist opens a quote, not checkout',await page.locator('#quoteDialog').isVisible());const txt=await page.locator('#quoteText').inputValue();ck('Florist receives the actual quantities and no other bouquet',txt.includes('5 × Pink lily')&&txt.includes('10 × Red rose')&&!txt.includes('CLASSIC ONLY'));ck('Estimate and no-order warnings are explicit',txt.includes('NOT AN ORDER')&&txt.includes('Sample prices')&&txt.includes('before any order or payment'));ck('Unconfigured WhatsApp and email are not faked',!await page.locator('#quoteWhatsApp').isVisible()&&!await page.locator('#quoteEmail').isVisible());
await page.locator('#quoteDate').fill('2020-01-01');await page.locator('#quoteMethod').selectOption('delivery');ck('Past date cannot be shared as a valid request',await page.locator('#downloadQuote').isDisabled());await page.locator('#quoteDate').fill('2030-09-20');await page.locator('#quoteMethod').selectOption('pickup');ck('Future request date enables export',await page.locator('#downloadQuote').isEnabled());
let dl=page.waitForEvent('download');await page.locator('#downloadQuote').tap();let d=await dl;await d.saveAs(path.join(root,'customer-florist-request.txt'));ck('Real request text download succeeds',(fs.readFileSync(path.join(root,'customer-florist-request.txt'),'utf8')).includes('2030-09-20'));
dl=page.waitForEvent('download');await page.locator('#quoteImage').tap();d=await dl;await d.saveAs(path.join(root,'customer-preview.png'));ck('Real image download succeeds',fs.statSync(path.join(root,'customer-preview.png')).size>5000);
await page.screenshot({path:path.join(root,'phone-quote.png')});await page.locator('[data-close=quoteDialog]').tap();await page.locator('#saveTop').tap();dl=page.waitForEvent('download');await page.locator('#saveJSON').tap();d=await dl;await d.saveAs(path.join(root,'three-bouquets.json'));const saved=JSON.parse(fs.readFileSync(path.join(root,'three-bouquets.json'),'utf8'));ck('JSON download includes all fixed-slot bouquets',saved.version===6&&saved.bouquets.dome.template.capacity===15&&saved.bouquets.heart.template.capacity===41);await page.locator('[data-close=saveDialog]').tap();
await page.locator('#language').selectOption('es');ck('Language changes copy without changing prices or flowers',await page.evaluate(()=>NebulaApp.lang==='es'&&NebulaModel.counts(NebulaApp.state).lily===5));await page.screenshot({path:path.join(root,'phone-spanish.png')});await page.locator('#language').selectOption('en');
for(const size of [{width:320,height:568},{width:360,height:800},{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(size);await page.waitForTimeout(150);const m=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,controls:document.getElementById('controls').getBoundingClientRect().height,canvas:document.getElementById('bouquet').getBoundingClientRect().width,footer:document.getElementById('reviewButton').getBoundingClientRect().bottom<=innerHeight+1}));ck('Usable viewport '+size.width+'x'+size.height,!m.overflow&&m.controls>90&&m.canvas>60&&m.footer,m);await page.screenshot({path:path.join(root,'phone-'+size.width+'x'+size.height+'.png')});}
ck('No page runtime errors in touch workflows',!errors.length,errors);await ctx.close();console.log('COMPLETE',checks.filter(c=>c.pass).length,'passed',checks.filter(c=>!c.pass).length,'failed');process.exit(0);
})().catch(async e=>{console.error(e.stack);if(page)await page.screenshot({path:path.join(root,'native-failure.png')}).catch(()=>{});if(ctx)await ctx.close().catch(()=>{});process.exit(1);});
