/* Lossless transport encoding only: no retouching, recoloring or background changes.
   Keeps supplied PNGs and their alpha; generates smaller web assets and file:// fallback. */
const fs=require('node:fs'),path=require('node:path'),sharp=require('sharp');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'assets/fall');
(async()=>{
 const embedded={},report=[];
 for(const name of ['rose-ivory-a','rose-ivory-b','orange-flower','wrap-cocoa','brown-bow','brown-ribbon','pumpkin','breath-airy','breath-wide','plush-snoopy','topper-snoopy','mum-burgundy','rose-caramel','plush-kitty']){
  const input=path.join(dir,name+'.png'),output=path.join(dir,name+'.webp');
  await sharp(input).webp({lossless:true,effort:6}).toFile(output);
  const bytes=fs.readFileSync(output),meta=await sharp(output).metadata();
  if(!meta.hasAlpha)throw Error('Alpha missing: '+name);
  embedded['assets/fall/'+name+'.webp']='data:image/webp;base64,'+bytes.toString('base64');
  report.push({name,inputBytes:fs.statSync(input).size,webBytes:bytes.length,width:meta.width,height:meta.height,alpha:meta.hasAlpha});
 }
 fs.writeFileSync(path.join(root,'fall-embedded.js'),'/* Local-file fallback only; generated by tools/prepare-fall.cjs. */\nObject.assign(window.NEBULA_EMBED,'+JSON.stringify(embedded)+');\n');
 fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(report,null,2));
 console.log(JSON.stringify({sourceBytes:report.reduce((a,v)=>a+v.inputBytes,0),webBytes:report.reduce((a,v)=>a+v.webBytes,0),assets:report.length}));
})().catch(e=>{console.error(e);process.exit(1)});
