/* Lossless delivery encoding; retain every visible pixel and the supplied alpha. */
const fs=require('node:fs'),path=require('node:path'),sharp=require('sharp');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'assets/romance');
(async()=>{
 const embedded={},report=[];
 for(const name of ['eucalyptus-sparse-a','eucalyptus-sparse-b','rose-red-cup-a','rose-red-cup-b']){
  const input=path.join(dir,name+'.png'),output=path.join(dir,name+'.webp');
  await sharp(input).webp({lossless:true,effort:6}).toFile(output);
  const a=await sharp(input).ensureAlpha().raw().toBuffer(),b=await sharp(output).ensureAlpha().raw().toBuffer(),m=await sharp(output).metadata();
  if(!m.hasAlpha||a.length!==b.length)throw Error('Invalid artwork: '+name);
  let transparent=0;
  for(let i=0;i<a.length;i+=4){if(a[i+3]!==b[i+3]||a[i+3]&&[0,1,2].some(c=>a[i+c]!==b[i+c]))throw Error('Pixel mismatch: '+name);if(!a[i+3])transparent++;}
  if(!transparent)throw Error('Opaque background: '+name);
  const bytes=fs.readFileSync(output);
  embedded['assets/romance/'+name+'.webp']='data:image/webp;base64,'+bytes.toString('base64');
  report.push({name,width:m.width,height:m.height,sourceBytes:fs.statSync(input).size,webBytes:bytes.length,transparentPixels:transparent,visiblePixelsAndAlphaExact:true});
 }
 fs.writeFileSync(path.join(root,'romance-embedded.js'),'/* Generated by tools/prepare-romance.cjs; local-file fallback only. */\nObject.assign(window.NEBULA_EMBED,'+JSON.stringify(embedded)+');\n');
 fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(report,null,2));
 console.log(JSON.stringify(report,null,2));
})().catch(e=>{console.error(e);process.exit(1)});
