/* Run with NODE_PATH pointing to Playwright and a local server at the given URL. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const root = path.resolve(__dirname, '../../..');
const output = path.join(__dirname, 'artifacts');
const url = process.argv[2] || 'http://127.0.0.1:8765/builder/3d.html';
const executablePath = process.env.BROWSER_PATH || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
(async () => {
  await fs.mkdir(output, { recursive: true });
  const browser = await chromium.launch({ executablePath, headless: true, args: ['--enable-webgl', '--use-gl=angle', '--use-angle=swiftshader'] });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1050 }, deviceScaleFactor: 1, acceptDownloads: true });
    const errors = [], failures = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('response', response => { if (response.status() >= 400) failures.push(response.url()); });
    await page.goto(url);
    await page.waitForFunction(() => !!window.Nebula3DStudio);
    await page.waitForTimeout(1200);
    assert.equal(await page.locator('#fallback3d').isVisible(), false, '3D renderer must open');
    assert.equal(await page.locator('#loading3d').isVisible(), false);
    assert.equal(await page.locator('#stemCount').textContent(), '15');
    assert.equal(await page.locator('#total3d').textContent(), '$86.00');
    assert.equal(await page.locator('#flowerGrid3d button').count(), 15);
    assert.deepEqual(await page.evaluate(() => { const ids = [...document.querySelectorAll('[id]')].map(e => e.id); return ids.filter((id, i) => ids.indexOf(id) !== i); }), []);
    await page.screenshot({ path: path.join(output, 'desktop.png') });
    const canvas = page.locator('#bouquet3d');
    const originalView = await canvas.evaluate(c => c.toDataURL());
    await page.locator('[data-view="side"]').click(); await page.waitForTimeout(900);
    assert.notEqual(await canvas.evaluate(c => c.toDataURL()), originalView, 'side camera changes the rendering');
    const sideView = await canvas.evaluate(c => c.toDataURL());
    await page.locator('#zoomIn3d').click(); await page.waitForTimeout(700);
    assert.notEqual(await canvas.evaluate(c => c.toDataURL()), sideView, 'zoom changes the rendering');
    await page.locator('#resetView3d').click(); await page.waitForTimeout(900);
    const beforeDrag = await canvas.evaluate(c => c.toDataURL());
    const bounds = await canvas.boundingBox();
    await page.mouse.move(bounds.x + bounds.width * .45, bounds.y + bounds.height * .5);
    await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width * .65, bounds.y + bounds.height * .48, { steps: 8 }); await page.mouse.up();
    await page.waitForTimeout(600);
    assert.notEqual(await canvas.evaluate(c => c.toDataURL()), beforeDrag, 'pointer drag orbits the camera');
    await canvas.focus(); const beforeKey = await canvas.evaluate(c => c.toDataURL());
    await canvas.press('ArrowLeft'); await page.waitForTimeout(600);
    assert.notEqual(await canvas.evaluate(c => c.toDataURL()), beforeKey, 'keyboard orbits the camera');
    await page.locator('#rotate3d').click();
    const beforeSpin = await canvas.evaluate(c => c.toDataURL()); await page.waitForTimeout(600);
    assert.notEqual(await canvas.evaluate(c => c.toDataURL()), beforeSpin, 'automatic rotation renders frames');
    await page.locator('#rotate3d').click();
    await page.locator('#resetView3d').click(); await page.waitForTimeout(900);
    await canvas.click({ position: { x: bounds.width * .5, y: bounds.height * .35 } });
    assert.equal(await page.locator('#selection3d').isVisible(), true, 'a flower can be selected in the 3D scene');
    await page.locator('#removeSelected3d').click();
    assert.equal(await page.locator('#stemCount').textContent(), '14');
    await page.locator('#undo3d').click();
    await page.evaluate(() => localStorage.setItem('nebulaBouquetV6', 'existing-photo-design-sentinel'));
    await page.locator('[data-flower="rose_pink"]').click();
    assert.equal(await page.locator('#stemCount').textContent(), '16');
    assert.equal(await page.locator('#total3d').textContent(), '$90.00');
    assert.equal(await page.locator('#toast3d').isVisible(), true);
    await page.locator('#undo3d').click();
    assert.equal(await page.locator('#stemCount').textContent(), '15');
    await page.locator('#redo3d').click();
    assert.equal(await page.locator('#stemCount').textContent(), '16');
    await page.locator('[data-tab="wrapping"]').click();
    await page.locator('[data-paper="sage"]').click();
    await page.locator('[data-ribbon="ivory"]').click();
    assert.equal(await page.evaluate(() => Nebula3DStudio.getDesign().paper), 'sage');
    await page.locator('[data-tab="details"]').click();
    await page.locator('[data-shape="heart"]').click();
    assert.equal(await page.locator('#total3d').textContent(), '$95.00');
    await page.locator('[data-view="top"]').click();
    await page.waitForTimeout(1300);
    await page.screenshot({ path: path.join(output, 'heart-top.png') });
    await page.locator('#designTitle').fill('A bouquet for you');
    await page.locator('#designTitle').press('Tab');
    await page.reload();
    await page.waitForFunction(() => !!window.Nebula3DStudio);
    assert.equal(await page.evaluate(() => Nebula3DStudio.getDesign().title), 'A bouquet for you');
    assert.equal(await page.evaluate(() => Nebula3DStudio.getDesign().shape), 'heart');
    assert.equal(await page.evaluate(() => localStorage.getItem('nebulaBouquetV6')), 'existing-photo-design-sentinel');
    await page.locator('#saveDesign').click();
    const jsonPromise = page.waitForEvent('download');
    await page.locator('#exportDesign3d').click();
    const jsonDownload = await jsonPromise;
    const json = JSON.parse(await fs.readFile(await jsonDownload.path(), 'utf8'));
    assert.equal(json.format, 'nebula-bouquet-3d');
    assert.equal(json.design.items.length, 16);
    await page.locator('#importFile3d').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"version":1}') });
    assert.equal(await page.evaluate(() => Nebula3DStudio.getDesign().items.length), 16);
    await page.locator('#importFile3d').setInputFiles({ name: 'saved.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(json)) });
    assert.equal(await page.locator('#saveDialog3d').isVisible(), false);
    const pngPromise = page.waitForEvent('download');
    await page.locator('#saveImage3d').click();
    const png = await fs.readFile(await (await pngPromise).path());
    assert.equal(png.subarray(1, 4).toString(), 'PNG');
    assert.equal(png.readUInt32BE(16), 1600); assert.equal(png.readUInt32BE(20), 1600);
    await fs.writeFile(path.join(output, 'export.png'), png);
    await page.locator('[data-tab="details"]').click();
    await page.locator('[data-remove="rose_pink"]').click();
    assert.equal(await page.locator('#stemCount').textContent(), '15');
    await page.locator('#clear3d').click(); await page.locator('#confirmClear3d').click();
    assert.equal(await page.locator('#total3d').textContent(), '$0.00');
    assert.equal(await page.locator('#empty3d').isVisible(), true);
    await page.locator('#undo3d').click();
    assert.equal(await page.locator('#stemCount').textContent(), '15');
    await page.locator('[data-tab="blooms"]').click();
    await page.locator('[data-preset="sunshine"]').click();
    await page.locator('#resetView3d').click();
    await page.waitForTimeout(1000);
    await page.screenshot({ path: path.join(output, 'sunshine.png') });
    for (let i = 15; i < 36; i++) await page.locator('[data-flower="rose_pink"]').click();
    assert.equal(await page.locator('#stemCount').textContent(), '36');
    assert.equal(await page.locator('[data-flower="rose_pink"]').isDisabled(), true);
    await page.locator('[data-preset="blush"]').click();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.waitForTimeout(600);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'phone horizontal overflow');
    await page.screenshot({ path: path.join(output, 'mobile.png') });
    await page.locator('[data-tab="wrapping"]').click();
    await page.locator('[data-paper="noir"]').click();
    assert.equal(await page.evaluate(() => Nebula3DStudio.getDesign().paper), 'noir');
    await page.locator('[data-tab="blooms"]').click();
    await page.locator('[data-family="tulip"]').click();
    assert.equal(await page.locator('#flowerGrid3d button').count(), 3);
    await page.locator('[data-flower="tulip_pink"]').click();
    assert.equal(await page.locator('#stemCount').textContent(), '16');
    // The legacy file-opening workflow is retained with local classic scripts.
    const filePage = await browser.newPage();
    await filePage.goto(pathToFileURL(path.join(root, 'builder/3d.html')).href);
    await filePage.waitForFunction(() => !!window.Nebula3DStudio);
    assert.equal(await filePage.locator('#fallback3d').isVisible(), false, 'direct-file WebGL must open');
    await filePage.close();
    const photoPage = await browser.newPage({ viewport: { width: 390, height: 844 } });
    await photoPage.goto(new URL('index.html', url).href);
    await photoPage.waitForFunction(() => !document.getElementById('saveTop').disabled);
    assert.equal(await photoPage.locator('a[href="3d.html"]').isVisible(), true);
    assert.equal(await photoPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'original photo studio keeps fitting phones');
    await photoPage.close();
    // Graceful fallback keeps saving and catalogue editing usable without WebGL.
    const fallback = await browser.newPage();
    await fallback.addInitScript(() => { const original = HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext = function (type, ...args) { return String(type).includes('webgl') ? null : original.call(this, type, ...args); }; });
    await fallback.goto(url);
    await fallback.waitForFunction(() => !!window.Nebula3DStudio);
    assert.equal(await fallback.locator('#fallback3d').isVisible(), true);
    assert.equal(await fallback.locator('#saveImage3d').isDisabled(), true);
    await fallback.close();
    assert.deepEqual(errors, []); assert.deepEqual(failures, []);
    console.log('PASS: desktop/mobile rendering, catalogue/pricing, edits/history, persistence/isolation, shapes/finishes, JSON import/export, PNG, capacity, file opening and WebGL fallback.');
    console.log('Screenshots: ' + output);
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
