const APP_URL=require('url').pathToFileURL(require('path').join(process.env.NEBULA_TEST_ROOT||require('path').resolve(__dirname,'../..'),'index.html')).href;
const {chromium}=require('playwright'),fs=require('fs'),path=require('path');let ctx;const rows=[],root=__dirname;
function ck(label,pass,detail){rows.push({label,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',label,detail??'');fs.writeFileSync(path.join(root,'edge-results.json'),JSON.stringify({passed:rows.filter(x=>x.pass).length,failed:rows.filter(x=>!x.pass).length,checks:rows},null,2));}
(async()=>{const b=await chromium.connectOverCDP(process.env.AGENT_BROWSER_CDP);ctx=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});let p=await ctx.newPage();await p.goto(APP_URL);await p.waitForFunction(()=>NebulaApp.ready);
let result=await p.evaluate(()=>{const M=NebulaModel,rows=[],ck=(label,pass)=>rows.push({label,pass});let s=M.defaultMode('heart');M.resize(s,100);ck('XL uses v1 zones, not a wall of resize overrides',Object.keys(s.template.overrides).length===0&&M.counts(s).sunflower===1&&M.counts(s).rose_red>0);M.updateTemplate(s,{zones:{...s.template.zones,wall:'rose_pink'}});ck('Heart wall still changes after resizing',!M.counts(s).rose_red&&M.counts(s).rose_pink>0);M.resize(s,8);ck('Mini heart retains its zone recipe',s.items.length===8&&M.counts(s).sunflower===1&&M.counts(s).rose_pink===7);
s=M.defaultMode('dome');M.resize(s,15);for(let i=0;i<5;i++)M.paintSlot(s,i,'lily');M.remove(s,'b8');M.resize(s,30);ck('Resize preserves five hand-painted lilies',M.counts(s).lily===5);ck('Resize preserves the intentional empty position',s.items.length===29&&Object.values(s.template.overrides).filter(x=>x===null).length===1);
let bad=M.clone(s);bad.template.overrides={'01':'lily'};ck('Noncanonical duplicate slot keys rejected',!M.validate(bad));bad=M.defaultMode('classic');bad.frames.classic.origin.x=1e30;ck('Impossible Classic paper transformations rejected',!M.validate(bad));
const raw=M.defaultMode('dome');raw.version=4;delete raw.template;raw.items.forEach(i=>delete i.slot);const mig=M.validate(raw);ck('Default v5 Dome migrates without blocking automatic blending',!!mig&&Object.keys(mig.template.overrides).length===0);M.updateTemplate(mig,{palette:['rose_red','rose_white']});ck('Migrated Dome can immediately blend varieties',M.counts(mig).rose_white>0);
const pf=M.portfolio(M.defaultMode('classic'),{dome:mig,heart:M.defaultMode('heart')});pf.version=5;Object.values(pf.bouquets).forEach(v=>{v.version=4;delete v.template;v.items.forEach(i=>delete i.slot);});ck('Old v5 studio imports all three bouquets',!!M.validatePortfolio(pf));
let seed=M.defaultMode('dome');seed.finishes.butterfly=true;ck('Explicit extras add only configured cost',M.price(seed).totalCents-M.price(M.defaultMode('dome')).totalCents===NebulaConfig.CONFIG.extrasCents.butterfly);return rows;});result.forEach(x=>ck(x.label,x.pass));
await p.evaluate(()=>{NebulaApp.setState(NebulaModel.defaultMode('dome'));NebulaApp.showQuote();});await p.locator('#copyQuote').click();const status=await p.locator('#quoteStatus').innerText();ck('Copy reports success or an honest manual fallback',/copied|selected|copy it/i.test(status),status);await p.locator('[data-close=quoteDialog]').click();
await p.evaluate(()=>{NebulaApp.setTool('paint');NebulaApp.chooseFlower('lily');});const before=await p.evaluate(()=>JSON.stringify(NebulaApp.state)),points=await p.evaluate(()=>{const s=NebulaApp.state,L=NebulaTemplates.layout(s.mode,s.template.capacity),r=document.getElementById('bouquet').getBoundingClientRect(),v=NebulaRenderer.view(s,NebulaApp.camera);return [0,1,2].map(i=>({x:r.left+(v.x+(360+L.points[i].x)*v.scale)*r.width/720,y:r.top+(v.y+(390+L.points[i].y)*v.scale)*r.height/820}));});const cd=await ctx.newCDPSession(p);await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[points[1]]});await cd.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});ck('Canceled paint gesture restores the complete design',await p.evaluate(()=>JSON.stringify(NebulaApp.state))===before);
await p.evaluate(()=>NebulaApp.stopBrush());await p.locator('#bouquet').focus();await p.keyboard.press('ArrowRight');await p.keyboard.press('Delete');ck('Keyboard can select and delete one fixed slot',await p.evaluate(()=>NebulaApp.state.items.length===29&&NebulaApp.state.template.capacity===30));await ctx.close();
// Synthetic owner configuration only; contact URLs are inspected, never followed or sent.
ctx=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await ctx.addInitScript(()=>{const conf={name:'Test florist',currency:'EUR',demo:false,whatsapp:'15555550123',email:'merchant@example.test',baseCents:3000,laborCents:{classic:900,dome:900,heart:1200},flowerPrices:{rose_red:700,lily:900}};Object.defineProperty(window,'NEBULA_SHOP',{get:()=>conf,set:()=>{},configurable:true});});p=await ctx.newPage();const external=[];await p.route(/^https?:\/\//,route=>{external.push(route.request().url());route.abort();});await p.goto(APP_URL);await p.waitForFunction(()=>NebulaApp.ready);const merchant=await p.evaluate(()=>{let s=NebulaModel.defaultMode('dome');NebulaModel.resize(s,15);for(let i=0;i<5;i++)NebulaModel.paintSlot(s,i,'lily');NebulaApp.setState(s);NebulaApp.showQuote();return {price:NebulaModel.price(s),title:document.title,brand:document.getElementById('brandName').textContent,wa:document.getElementById('quoteWhatsApp').href,email:document.getElementById('quoteEmail').href,text:document.getElementById('quoteText').value};});ck('Owner flower rates recalculate exact mixed estimate',merchant.price.totalCents===15400,merchant.price.totalCents);ck('Approved prices remove the sample flag',merchant.price.demo===false&&!merchant.text.includes('Sample prices'));ck('Currency follows owner configuration without conversion',merchant.price.currency==='EUR');ck('Shop branding comes from one owner file',merchant.brand==='Test florist'&&merchant.title.startsWith('Test florist'));
ck('WhatsApp opens only a customer-reviewed draft',merchant.wa.startsWith('https://wa.me/15555550123?text=')&&decodeURIComponent(merchant.wa).includes('NOT AN ORDER'));ck('Email is an encoded draft, not auto-send',merchant.email.startsWith('mailto:merchant@example.test?subject=')&&merchant.email.includes('&body='));ck('No external contact or analytics request was made',external.length===0,external);await ctx.close();
ctx=await b.newContext();await ctx.addInitScript(()=>{Object.defineProperty(window,'NEBULA_SHOP',{get:()=>({currency:'not-money',whatsapp:'javascript:alert(1)',email:'bad@example.test?body=x',baseCents:-1,flowerPrices:{rose_red:-8}}),set:()=>{},configurable:true});});p=await ctx.newPage();await p.goto(APP_URL);await p.waitForFunction(()=>NebulaApp.ready);const invalid=await p.evaluate(()=>({c:NebulaConfig.CONFIG,rose:NebulaConfig.CAT.rose_red.priceCents}));ck('Invalid contact destinations are disabled',invalid.c.whatsapp===''&&invalid.c.email==='');ck('Invalid prices and currency fall back safely',invalid.c.currency==='USD'&&invalid.c.baseCents===2500&&invalid.rose===400&&invalid.c.demo===true);await ctx.close();console.log('COMPLETE',rows.filter(r=>r.pass).length,'passed',rows.filter(r=>!r.pass).length,'failed');process.exit(0);
})().catch(async e=>{console.error(e.stack);if(ctx)await ctx.close().catch(()=>{});process.exit(1);});
