/* SHOP OWNER: approved integer cents, no automatic currency conversion. See SHOP-SETUP.md.
   No passwords or API keys belong in this public file. Keep demo:true until prices are reviewed. */
window.NEBULA_SHOP={name:'Nebula',
  studio:{name:'Nebula Sites Studio',site:'nebulastudio.site/flowers',
          phone:'(571) 336-7129',instagram:'@nebulaa_studio',
          place:'Virginia, USA — serving businesses across the US',year:'2026'},currency:'USD',demo:true,whatsapp:'',email:'',baseCents:2500,laborCents:{classic:1000,dome:1000,heart:1500},extrasCents:{butterfly:300,ribbon:0,sash:0},flowerPrices:{
  "rose_red": 400,
  "rose_pink": 400,
  "rose_white": 400,
  "rose_violet": 400,
  "rose_yellow": 400,
  "rose_orange": 400,
  "tulip_red": 300,
  "tulip_pink": 300,
  "tulip_white": 300,
  "tulip_violet": 300,
  "tulip_yellow": 300,
  "tulip_orange": 300,
  "carnation_red": 250,
  "carnation_pink": 250,
  "carnation_white": 250,
  "carnation_violet": 250,
  "carnation_yellow": 250,
  "carnation_orange": 250,
  "lily": 500,
  "gerbera_daisy": 400,
  "sunflower": 400,
  "ranunculus": 500,
  "alstroemeria": 300,
  "eucalyptus": 200,
  "statice_purple": 200,
  "babys_breath": 200,
  "hydrangea": 650,
  "chrysanthemum_yellow": 400,
  "spray_rose": 450,
  "stock_yellow": 350,
  "rose_cream": 400,
  "__choc": 500
}};
