/* Targeted regressions for customer-facing launch hardening. No messages sent. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.BUILDER_URL||'http://127.0.0.1:8767/builder/',checks=[],out=path.join(__dirname,'launch-final');fs.mkdirSync(out,{recursive:true});
function check(name,ok){assert.ok(ok,name);checks.push(name);console.log('PASS',name);}
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{
 const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));let failBlue=true;
 await p.route('**/assets/halloween/blue-thistle.webp',route=>failBlue?route.abort():route.continue());
 await p.goto(base);await p.waitForFunction(()=>NebulaApp?.ready);const mid=p.locator('[data-template=midnight-blooms]');await mid.locator('xpath=..').getByRole('status').waitFor({state:'visible'});
 check('Failed preview offers an enabled retry',await mid.isEnabled()&&await mid.getAttribute('data-retry')==='true');
 check('One failed optional asset does not block unrelated bouquets',await p.locator('[data-template=scream-for-you]').isEnabled()&&await p.locator('[data-template=forever-my-boo]').isEnabled());
 failBlue=false;await mid.click();await p.waitForFunction(()=>!document.querySelector('[data-template=midnight-blooms]').dataset.retry&&!document.querySelector('[data-template=midnight-blooms]').disabled);
 check('Retry restores artwork without accidentally opening a different design',await p.locator('#templateGallery').isVisible()&&await p.evaluate(()=>NebulaApp.state.mode==='classic'));
 await mid.click();check('Recovered card opens its bouquet',await p.evaluate(()=>NebulaApp.state.template.halloweenRecipe==='midnight-blooms'));
 check('Gallery buttons and previews have specific accessible names',await p.evaluate(()=>[...document.querySelectorAll('[data-template]')].every(el=>el.getAttribute('aria-label')?.includes(el.closest('article').querySelector('h3').textContent))&&document.querySelectorAll('.fall-template-card canvas[role=img]').length===10));
 check('Shared links reject fractional, zero, coerced and excessive quantities',await p.evaluate(()=>{const raw=JSON.parse(atob(NebulaLink.encode(NebulaSpooky.create('scream-for-you')).replace(/-/g,'+').replace(/_/g,'/'))),encode=o=>btoa(JSON.stringify(o));return [0,-1,.5,1.5,'30',101,null].every(n=>{const p=structuredClone(raw);p.f[0][1]=n;return NebulaLink.decode(encode(p))===null;})&&NebulaLink.decode('x'.repeat(24001))===null;}));
 await p.evaluate(()=>NebulaApp.applyFallTemplate('forever-my-boo'));
 const original=await p.evaluate(()=>JSON.stringify(NebulaApp.state));
 await p.evaluate(()=>{const original=NebulaRenderer.blob;NebulaRenderer.blob=async(...args)=>{window.__exportInput=JSON.stringify(args[0]);await new Promise(resolve=>window.__releaseExport=resolve);return original(...args);};Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:async payload=>{window.__sharedPayload={text:payload.text,title:payload.title,bytes:payload.files[0].size};}});});
 await p.locator('#saveTop').click();await p.locator('#shareButton').click();await p.waitForFunction(()=>window.__releaseExport);
 await p.evaluate(()=>{NebulaApp.paintSlot(0,'rose_ivory');window.__releaseExport();});await p.waitForFunction(()=>window.__sharedPayload);
 check('Image and link retain the same snapshot while a design changes',await p.evaluate(original=>{const shared=NebulaLink.decode(NebulaLink.readHash(window.__sharedPayload.text)).design;return window.__exportInput===original&&JSON.stringify(shared.items)===JSON.stringify(JSON.parse(original).items)&&window.__sharedPayload.bytes>10000&&NebulaApp.state.items.find(n=>n.slot===0).id==='rose_ivory';},original));
 await p.locator('[data-close=saveDialog]').click();await p.locator('#tab-finishing').click();
 check('Halloween detail controls display their unit prices',await p.locator('#ghostCountPrice').innerText().then(t=>t.includes('$1.00')));
 await p.locator('#ghostCount').fill('0');await p.locator('#ghostCount').dispatchEvent('change');await p.locator('#tab-wrapping').click();await p.locator('#showCollar').uncheck();
 const code=await p.evaluate(()=>NebulaLink.encode(NebulaApp.state));const order=await ctx.newPage();await order.goto(base+'order.html#b='+code);await order.waitForSelector('#orderSheet:not([hidden])');check('Florist sheet does not list wrapping removed by the customer',!(await order.locator('#osFinishes').innerText()).includes('Wrapping:'));await order.close();
 const hash=await p.evaluate(()=>NebulaLink.encode(NebulaSpooky.create('midnight-blooms'))),boot=await ctx.newPage();let startupFail=true;boot.on('pageerror',e=>errors.push(e.message));await boot.route('**/assets/halloween/blue-thistle.webp',route=>startupFail?route.abort():route.continue());await boot.goto(base+'#b='+hash);await boot.locator('#startupError').waitFor({state:'visible'});check('A shared design that cannot load has a visible retry control',await boot.locator('#retryStartup').isEnabled());startupFail=false;await boot.locator('#retryStartup').click();await boot.waitForFunction(()=>NebulaApp.ready);check('Startup retry restores the original shared design',await boot.evaluate(()=>NebulaApp.state.items.length===20&&NebulaApp.state.template.halloweenRecipe==='midnight-blooms')&&await boot.locator('#startupError').isHidden());await boot.close();
 await p.setViewportSize({width:320,height:844});await p.evaluate(()=>NebulaApp.applyFallTemplate('scream-for-you'));await p.locator('#tab-finishing').click();check('320px finishing controls fit and retain translated prices',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)&&await p.locator('#spookyMaskPrice').innerText().then(t=>t.includes('$20.00')));await p.screenshot({path:path.join(out,'finishing-320.png'),fullPage:true});
 await p.evaluate(()=>NebulaApp.showGallery(true));await p.setViewportSize({width:1440,height:1000});await p.screenshot({path:path.join(out,'gallery-desktop.png'),fullPage:true});
 check('Handled download failures produce no uncaught runtime errors',errors.length===0);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
