const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),{pathToFileURL}=require('node:url'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const info=JSON.parse(fs.readFileSync(path.join(__dirname,'launch-final/package.json'),'utf8')),root=path.join(info.work,'extracted','nebula-bouquet-studio'),checks=[];
function check(name,ok){assert.ok(ok,name);checks.push(name);console.log('PASS',name);}
(async()=>{
 check('Extracted ZIP exactly matches all delivery-file hashes',Object.entries(info.hashes).every(([rel,hash])=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,rel))).digest('hex')===hash));
 const server=http.createServer((req,res)=>{try{let file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep)&&file!==root)return res.writeHead(403).end();if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.jpg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{
 for(const mode of ['http','file']){const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),p=await ctx.newPage(),errors=[],failures=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>failures.push(r.url()));p.on('response',r=>{if(r.status()>=400)failures.push(r.url());});await p.route(/^https?:\/\//,r=>{if(r.request().url().startsWith(origin))r.continue();else{external.push(r.request().url());r.abort();}});
 await p.goto(mode==='http'?origin+'/index.html':pathToFileURL(path.join(root,'index.html')).href);await p.waitForFunction(()=>NebulaApp?.ready);await p.waitForFunction(()=>document.querySelectorAll('[data-template]:not(:disabled):not([data-retry])').length===10);
 check(mode+': ten complete previews in a clean extraction',await p.locator('[data-template]').count()===10);
 await p.locator('[data-preview=scream-for-you]').click();await p.waitForFunction(()=>document.getElementById('collectionPreviewImage').naturalWidth>0);check(mode+': packaged style photograph loads',await p.locator('#collectionPreviewImage').getAttribute('src').then(s=>s.endsWith('scream-for-you.jpg')));await p.locator('#collectionPreviewDesign').click();await p.waitForFunction(()=>document.getElementById('collectionPreviewImage').naturalWidth===1080);
 check(mode+': enlarged bouquet preview uses packaged artwork and exact ingredients',await p.locator('#collectionPreviewImage').getAttribute('src').then(s=>s.startsWith('data:image/png'))&&await p.locator('#collectionPreviewItems').innerText().then(s=>s.includes('30 × Red rose')&&s.includes('Scream mask')));await p.locator('[data-close=collectionPreviewDialog]').click();
 check(mode+': all recipes retain exact scenes and prices through links',await p.evaluate(async()=>{for(const collection of [NebulaRomance,NebulaFall,NebulaSpooky])for(const recipe of collection.recipes){const s=collection.create(recipe.id);await NebulaRenderer.awaitAssets(s);const d=NebulaLink.decode(NebulaLink.encode(s))?.design;if(!d||JSON.stringify(NebulaRenderer.scene(s))!==JSON.stringify(NebulaRenderer.scene(d))||JSON.stringify(NebulaModel.price(s))!==JSON.stringify(NebulaModel.price(d)))return false;}return true;}));
 check(mode+': legacy Classic, Dome and Heart still validate and export',await p.evaluate(async()=>{for(const mode of ['classic','dome','heart']){const s=NebulaModel.defaultMode(mode);if(!NebulaModel.validate(s)||!NebulaLink.decode(NebulaLink.encode(s)))return false;const png=await NebulaRenderer.blob(s,540,540,'en');if(png.size<10000)return false;}return true;}));
 check(mode+': new Halloween square and story PNGs export',await p.evaluate(async()=>{for(const size of [[1080,1080],[1080,1920]]){const b=await NebulaRenderer.blob(NebulaSpooky.create('midnight-blooms'),...size,'en');if(b.size<10000)return false;}return true;}));
 check(mode+': no missing resources, external dependencies or uncaught errors',!errors.length&&!failures.length&&!external.length);await ctx.close();}
 fs.writeFileSync(path.join(__dirname,'launch-final/release-results.json'),JSON.stringify({files:info.files,checks},null,2));
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(e=>{console.error(e);process.exit(1)});
