/* Ramos by Julia — shop-config.js
   Gresham & Rockwood, Oregon · @ramos_by_juliaaa */
window.NEBULA_SHOP = {
  name: 'Ramos by Julia',
  studio: {
    name: 'Ramos by Julia',
    site: 'nebulastudio.site/demo/jullyflowershop/',
    phone: '(503) 555-0144',
    instagram: '@ramos_by_juliaaa',
    place: 'Gresham & Rockwood, Oregon',
    year: '2026'
  },
  currency: 'USD',
  demo: false,
  whatsapp: '',
  email: 'ramosbyjulia@gmail.com',
  baseCents: 0,
  laborCents: { classic: 1000, dome: 1000, heart: 1500 },
  extrasCents: { butterfly: 500, ribbon: 0, sash: 500 },
  flowerPrices: {
    "rose_red": 210,
    "rose_pink": 210,
    "rose_white": 210,
    "rose_violet": 210,
    "rose_yellow": 210,
    "rose_orange": 210,
    "rose_cream": 210,
    "tulip_red": 200,
    "tulip_pink": 200,
    "tulip_white": 200,
    "tulip_violet": 200,
    "tulip_yellow": 200,
    "tulip_orange": 200,
    "carnation_red": 180,
    "carnation_pink": 180,
    "carnation_white": 180,
    "carnation_violet": 180,
    "carnation_yellow": 180,
    "carnation_orange": 180,
    "lily": 400,
    "gerbera_daisy": 350,
    "sunflower": 350,
    "ranunculus": 400,
    "alstroemeria": 250,
    "eucalyptus": 200,
    "statice_purple": 200,
    "babys_breath": 200,
    "hydrangea": 500,
    "chrysanthemum_yellow": 300,
    "spray_rose": 350,
    "stock_yellow": 300,
    "__choc": 500
  }
};
